-- Staging: one row per player ("element" in API terms), typed and renamed.
--
-- The API sends most rate metrics (form, ict_index, expected_goals, ...) as STRINGS.
-- This is the single place they are cast to numbers, so every downstream model can trust types.
-- now_cost is in tenths of a million (55 = £5.5m); price_m is the human-readable version.
SELECT
    id                                                  AS player_id,
    code                                                AS player_code,
    web_name,
    first_name,
    second_name,
    team                                                AS team_id,
    element_type                                        AS position_id,
    status,                                             -- a=available, d=doubtful, i=injured, s=suspended, u=unavailable, n=not in squad
    chance_of_playing_next_round,                       -- NULL means "no news" i.e. fully fit
    chance_of_playing_this_round,
    news,
    CAST(news_added AS TIMESTAMPTZ)                     AS news_added_ts,
    now_cost,
    now_cost / 10.0                                     AS price_m,
    cost_change_start / 10.0                            AS price_change_since_start_m,
    cost_change_event / 10.0                            AS price_change_this_gw_m,
    TRY_CAST(selected_by_percent AS DOUBLE)             AS selected_by_pct,
    transfers_in_event,
    transfers_out_event,
    transfers_in_event - transfers_out_event            AS net_transfers_event,
    total_points,
    event_points                                        AS last_gw_points,
    TRY_CAST(points_per_game AS DOUBLE)                 AS points_per_game,
    TRY_CAST(form AS DOUBLE)                            AS form,               -- API: avg points over last 30 days
    TRY_CAST(ep_next AS DOUBLE)                         AS api_ep_next,        -- API's own expected points next GW (benchmark)
    TRY_CAST(ep_this AS DOUBLE)                         AS api_ep_this,
    TRY_CAST(value_form AS DOUBLE)                      AS value_form,
    TRY_CAST(value_season AS DOUBLE)                    AS value_season,
    minutes,
    starts,
    goals_scored,
    assists,
    clean_sheets,
    goals_conceded,
    own_goals,
    penalties_saved,
    penalties_missed,
    yellow_cards,
    red_cards,
    saves,
    bonus,
    bps,
    defensive_contribution,
    TRY_CAST(influence AS DOUBLE)                       AS influence,
    TRY_CAST(creativity AS DOUBLE)                      AS creativity,
    TRY_CAST(threat AS DOUBLE)                          AS threat,
    TRY_CAST(ict_index AS DOUBLE)                       AS ict_index,
    TRY_CAST(expected_goals AS DOUBLE)                  AS xg,
    TRY_CAST(expected_assists AS DOUBLE)                AS xa,
    TRY_CAST(expected_goal_involvements AS DOUBLE)      AS xgi,
    TRY_CAST(expected_goals_conceded AS DOUBLE)         AS xgc,
    TRY_CAST(expected_goals_per_90 AS DOUBLE)           AS xg_per_90,
    TRY_CAST(expected_assists_per_90 AS DOUBLE)         AS xa_per_90,
    TRY_CAST(expected_goal_involvements_per_90 AS DOUBLE) AS xgi_per_90,
    TRY_CAST(expected_goals_conceded_per_90 AS DOUBLE)  AS xgc_per_90,
    TRY_CAST(saves_per_90 AS DOUBLE)                    AS saves_per_90,
    TRY_CAST(clean_sheets_per_90 AS DOUBLE)             AS clean_sheets_per_90,
    TRY_CAST(starts_per_90 AS DOUBLE)                   AS starts_per_90,
    TRY_CAST(defensive_contribution_per_90 AS DOUBLE)   AS defensive_contribution_per_90,
    penalties_order,
    corners_and_indirect_freekicks_order,
    direct_freekicks_order,
    dreamteam_count,
    snapshot_id
FROM raw.players
